1725254310652	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1725254320991	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1725254321043	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1725254321134	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1725254321265	Sync.SyncScheduler	DEBUG	Woke from sleep.
1725254321270	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1725254321340	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1725254321340	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1725254321342	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1725254323346	Sync.Service	DEBUG	User-Agent: Firefox/129.0.2 (Linux x86_64) FxSync/1.131.0.20240820123043.desktop
1725254323347	Sync.Service	INFO	Starting sync at 2024-09-02 10:48:43 in browser session lmOE9UNwGi5l
1725254323350	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1725254323439	Sync.Status	INFO	Resetting Status.
1725254323439	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1725254323448	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1725254323468	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/261848012/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1725254323470	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1725254323470	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1725254323471	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1725254323477	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1725254323490	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
