1725347786463	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1725347793974	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1725347793987	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1725347794009	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1725347794023	Sync.SyncScheduler	DEBUG	Woke from sleep.
1725347794025	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1725347794049	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1725347794050	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1725347794050	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1725347796052	Sync.Service	DEBUG	User-Agent: Firefox/129.0.2 (Linux x86_64) FxSync/1.131.0.20240820123043.desktop
1725347796052	Sync.Service	INFO	Starting sync at 2024-09-03 12:46:36 in browser session Ki2_dpovZ5cP
1725347796052	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1725347796065	Sync.Status	INFO	Resetting Status.
1725347796065	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1725347796067	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1725347796073	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/261848012/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1725347796073	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1725347796073	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1725347796074	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1725347796075	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1725347796078	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
