1724958929751	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1724958929753	Sync.Engine.Tabs	INFO	Uploading 1 outgoing records
1724958929753	Sync.Engine.Tabs	INFO	Posting 1 records of 9219 bytes with batch=true
1724958929754	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1724958929754	Sync.Collection	DEBUG	POST Length: 9219
1724958930081	Sync.Collection	DEBUG	POST success 200 https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/261848012/storage/tabs?batch=true&commit=true
1724958930091	Sync.Telemetry	INFO	Observed notification weave:engine:sync:uploaded but no current sync is being recorded.
1724958941649	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1724958941656	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1724958941680	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1724958941691	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1724958941695	Sync.SyncScheduler	DEBUG	Woke from sleep.
1724958941736	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1724958941736	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1724958941737	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1724958943804	Sync.Service	DEBUG	User-Agent: Firefox/129.0.2 (Linux x86_64) FxSync/1.131.0.20240820123043.desktop
1724958943804	Sync.Service	INFO	Starting sync at 2024-08-30 00:45:43 in browser session eVLlafOCePno
1724958943805	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1724958943810	Sync.Status	INFO	Resetting Status.
1724958943810	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1724958943811	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1724958943830	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/261848012/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1724958943830	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1724958943831	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1724958943831	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1724958943832	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1724958943834	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
