1723608711476	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1723609362261	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1723609362261	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1723609362262	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1723609362263	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1723609362283	Sync.SyncScheduler	DEBUG	Woke from sleep.
1723609362285	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1723609362285	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1723609362285	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1723609362378	Sync.Service	DEBUG	User-Agent: Firefox/129.0 (Linux x86_64) FxSync/1.131.0.20240806001732.desktop
1723609362378	Sync.Service	INFO	Starting sync at 2024-08-14 09:52:42 in browser session kNV2EeDMaxEx
1723609362378	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1723609362379	Sync.Status	INFO	Resetting Status.
1723609362379	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1723609362379	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1723609362379	FirefoxAccounts	DEBUG	getOAuthToken enter
1723609362380	FirefoxAccounts	TRACE	getCachedToken returning cached token
1723609362380	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1723609362380	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1723609366148	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1723609366148	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1723609366148	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1723609366149	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1723609366150	Sync.Service	DEBUG	User-Agent: Firefox/129.0 (Linux x86_64) FxSync/1.131.0.20240806001732.desktop
1723609366150	Sync.Service	INFO	Starting sync at 2024-08-14 09:52:46 in browser session kNV2EeDMaxEx
1723609366150	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.sys.mjs:43:5) JS Stack trace: LockException@util.sys.mjs:43:5
throwLockException@util.sys.mjs:127:11
WrappedLock@util.sys.mjs:141:15
_lockedSync@service.sys.mjs:1372:6
sync/<@service.sys.mjs:1337:18
WrappedCatch@util.sys.mjs:112:27
sync@service.sys.mjs:1338:7
1723609366150	Sync.Service	INFO	Cannot start sync: already syncing?
1723609368047	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1723609370415	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1723609377386	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1723609377386	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.sys.mjs :: onStopRequest :: line 478\"  data: no]"}
1723609382391	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/261848012/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1723609382391	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1723609382391	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1723609382392	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1723609382392	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1723609382394	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
